[package]
name = "solana-token-metadata"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-sdk = "1.17.0"
solana-client = "1.17.0"
spl-token = "4.0.0"
mpl-token-metadata = "3.2.0"
anyhow = "1.0.75"
tokio = { version = "1.32.0", features = ["full"] }
